//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Models.BankEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int contact_id { get; set; }
        public int userid { get; set; }
        public string email_address { get; set; }
        public string phone_number { get; set; }
        public string social_security_number { get; set; }
    
        public virtual User User { get; set; }
    }
}
