//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Models.BankEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transact_id { get; set; }
        public int account_id { get; set; }
        public string transact_name { get; set; }
        public string transact_desc { get; set; }
        public string transact_type { get; set; }
        public decimal transact_amount { get; set; }
        public System.DateTime transact_date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
